ess-dmsc/NeXus-Streamer

- event_data/src/DetectorSpectrumMapData.cpp
- event_data/src/EventData.cpp
- nexus_file_reader/include/NexusFileReader.h
- nexus_file_reader/src/NexusFileReader.cpp
- nexus_file_reader/test/NexusFileReaderTest.cpp
- nexus_producer/test/NexusPublisherTest.cpp
Changes make pulse timestamps look like the data is coming from a live instrument rather than using the historical time from the NeXus file.
Closes #23
Review code and check unit tests pass.
---
---
> Make pulse times look live

- Jenkinsfile
> Replacing fedora build node with debian9

- README.md
- nexus_producer/src/main.cpp
Adding flags to CLI11 arguments that are required. 
Also updated the README to show arguments that are optional. 
Closes #29 
`main.cpp`
`README.md`
---
---
> Adding required flag to non-optional arguments

- README.md
Adding `.ini` example showing some options that the streamer can be started with. 
Closes #30 
---
---
> Adding .ini file example to README.md

- data/convert_hdf5_file_to_uncompressed.py
- data/nexus_recompress.py
- data/nexus_recompress_all.py
- data/reduce_hdf5_file.py
- data/requirements.txt
converting scripts to Python3
Closes #14 
---
---
> Adding requirements.txt and converting scripts to Python 3

- README.md
Adding a section in the readme for setting conan up if compiler settings are not detected. 
Closes #33 
---
---
> Adding conan profile info for when compiler settings are not detected

- Jenkinsfile
Closes #57 
Only does the release build and archives the build artefact on PR builds.
> Only do release build and archive artefact on PR builds

- Jenkinsfile
PR builds get deleted after merging the feature branch, so we have to revert to creating the artifact on every commit build.
Closes #61
Check artifact gets created on normal branch builds.
---
---
> Revert build artifact only being created on PR builds

- CMakeLists.txt
- event_data/include/SampleEnvironmentEvent.h
- event_data/include/SampleEnvironmentEventDouble.h
- event_data/include/SampleEnvironmentEventInt.h
- event_data/include/SampleEnvironmentEventLong.h
- event_data/test/SampleEnvironmentEventTest.cpp
- nexus_file_reader/include/NexusFileReader.h
- nexus_file_reader/src/NexusFileReader.cpp
- nexus_producer/src/NexusPublisher.cpp
Use `-Wall` and `-Werror` flags to add more warnings and treat them as errors.
Closes #59
Jenkins builds must pass.
---
---
> Add more compiler warnings

- README.md
Add docker hub link and description and location of example `ini` file.
Closes #64 
Closes #67 
No changes in functionality.
None modified.
N/A
---
---
> Add docker hub section and ini example in readme

- Dockerfile
Modifying Dockerfile to use the json registry for conan rather than the txt registry.
Closes #67 
No functional changes. 
None modified. 
N/A.
---
---
> Use json registry for conan in dockerfile

- README.md
- docker/example_config.ini
- nexus_producer/src/main.cpp
Renaming CLI arg `config_file` to `config-file` for consistency with other projects
Closes #65 
No functional changes besides parsing the config `ini`
None modified. 
Updated README to reflect changes 
---
---
> Renaming config_file to config-file

- conan/conanfile.txt
- nexus_file_reader/CMakeLists.txt
- nexus_file_reader/include/NexusFileReader.h
- nexus_file_reader/src/NexusFileReader.cpp
- nexus_producer/CMakeLists.txt
- nexus_producer/include/KafkaEventPublisher.h
- nexus_producer/include/NexusPublisher.h
- nexus_producer/src/KafkaEventPublisher.cpp
- nexus_producer/src/NexusPublisher.cpp
- nexus_producer/src/main.cpp
- unitTestRunner.cpp
Use spdlog rather than just `std::cout`.
Closes #78
---
---
> Use spdlog

- Jenkinsfile
Removing the slack calls that were clogging up the Jenkins channel. 
---
---
> Remove slack calls 

- nexus_file_reader/src/NexusFileReader.cpp
- nexus_file_reader/test/HDF5FileTestHelpers.cpp
- nexus_file_reader/test/HDF5FileTestHelpers.h
- nexus_file_reader/test/NexusFileReaderTest.cpp
Cope with event_time_zero dataset having units of seconds or nanoseconds.
Closes #99
*List the changes in functionality or code that the reviewer needs to review.*
*Give an overview of any unit tests you have added or modified, if applicable.*
*Give information on anything else that might be relevant to the reviewer. Such as added system tests, update documentation etc.*
---
---
> 99 get frame time should repect units

- CMakeLists.txt
- Dockerfile
- conan/conanfile.txt
- nexus_producer/CMakeLists.txt
- nexus_producer/src/KafkaEventPublisher.cpp
Increases allowed message size, we want to test with higher event rates.
Updates version of CLI11 used.
Closes #104
---
---
> Increase max message size

- nexus_file_reader/CMakeLists.txt
- nexus_file_reader/include/UnitConversion.h
- nexus_file_reader/src/NexusFileReader.cpp
- nexus_file_reader/src/UnitConversion.cpp
- nexus_file_reader/test/UnitConversionTest.cpp
Refactor unit conversions to separate file, add unit tests and fix bug.
Closes #109
Check tests are clear.
---
---
> Refactor unit conversions to separate file and add unit tests

- nexus_producer/src/KafkaPublisher.cpp
*Add your own description here. The aim is provide information to help the reviewer review the PR.*
*If there is an associated issue, write 'Closes #XXX'*
*List the changes in functionality or code that the reviewer needs to review.*
*Give an overview of any unit tests you have added or modified, if applicable.*
*Give information on anything else that might be relevant to the reviewer. Such as added system tests, update documentation etc.*
---
---
> Increase allowed size to 200MB for LOKI description

- conan/conanfile.txt
Bump librdkafka to 1.1.0, as recommended by Lamar at V20.
Closes JIRA issue LDPC-157.
Tests should still pass; no changes have been made to the source code.
n/a
n/a
---
---
> Bump librdkafka version

- CMakeLists.txt
- conan/conanfile.txt
- nexus_producer/include/NexusPublisher.h
- nexus_producer/src/NexusPublisher.cpp
- nexus_producer/test/NexusPublisherTest.cpp
- serialisation/CMakeLists.txt
- serialisation/include/DetectorSpectrumMapData.h
- serialisation/include/RunData.h
- serialisation/include/UUID.h
- serialisation/src/DetectorSpectrumMapData.cpp
- serialisation/src/RunData.cpp
- serialisation/src/UUID.cpp
- serialisation/test/DetectorSpectrumMapDataTest.cpp
- serialisation/test/RunDataTest.cpp
Updated to new run start and stop schema.
Updated dependencies to our current recommended versions.
DM-1846
Closes #106
> Update run start and stop message schema

- Dockerfile
- README.md
- generate_json/generate_json_description.py
- generate_json/requirements.txt
The Dockerfile and python generation of the nexus_structure had broken due to docker image and nexus library updates.
> Update dockerfile for gcc8

- CMakeLists.txt
- cmake/Versioning.cmake
- cmake/templates/Version.h.in
- nexus_producer/CMakeLists.txt
- nexus_producer/src/main.cpp
Added Afonso's cmake scripts for versioning.
`--version` opt arg supported.
> Add versioning

- CMakeLists.txt
- conan/conanfile.txt
- nexus_producer/CMakeLists.txt
Update Conan dependencies for replacing Bintray.
ECDC-2300
Functionality should not change.
n/a
n/a
---
---
> Replace Bintray
